[package]
name    = "esp32_nostd_mqtt"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
panic-halt   = "0.2"
esp32-hal = { package = "esp32-hal", git = "https://github.com/esp-rs/esp-hal.git", rev = "907d43ed6f2bfde73763f9465b3e044c7777fee6" }
xtensa-lx-rt = { version = "0.12.0", features = ["esp32"], optional = true }

esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = ["esp32", "embedded-svc"] }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
embedded-svc = { version = "0.22.0", default-features = false }
mqttrust = "0.5.1"
log = "0.4.16"
nb = "1.0.0"
embedded-hal = "0.2"
esp-println = { version = "0.2.0", features = [ "esp32" ] }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace.git", features = [ "esp32", "panic-handler" ] }

[features]
default = ["rt"]
rt = ["xtensa-lx-rt"]
