[package]
name    = "esp32_nostd_mqtt"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
panic-halt   = "0.2"
esp32-hal = { package = "esp32-hal", git = "https://github.com/esp-rs/esp-hal.git" }
xtensa-lx-rt = { version = "0.11.0", features = ["esp32"], optional = true }

esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = ["esp32", "embedded-svc"] }
smoltcp = { version = "0.8.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
smoltcp-nal = "0.2.1"
embedded-time = "0.12.1"
embedded-nal = "0.6.0"
embedded-svc = { version = "0.20.3", default-features = false, features = [ "alloc" ] }
mqttrust = "0.5.1"
log = "0.4.16"
nb = "1.0.0"
embedded-hal = "0.2"

[features]
default = ["rt"]
rt = ["xtensa-lx-rt"]
