[target.xtensa-esp32-none-elf]
runner = "espflash --speed 921600 --monitor"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-Tesp32_rom_functions.x",
]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
